import pydot
# graph = pydot.Dot(graph_type='digraph',, size="1920,1080" )
graph = pydot.Dot(graph_type='digraph', rankdir='LR')
edge = pydot.Edge("Hari 1", "Basic Python Syntaxes")
graph.add_edge(edge)
edge = pydot.Edge("Basic Python Syntaxes", "Sequential Code")
graph.add_edge(edge)
edge = pydot.Edge("Basic Python Syntaxes", "Branching with IF")
graph.add_edge(edge)
edge = pydot.Edge("Basic Python Syntaxes", "Looping with For and While")
graph.add_edge(edge)

edge = pydot.Edge("Hari 1", "Modularization - Function")
graph.add_edge(edge)
edge = pydot.Edge("Hari 1", "Modularization - Class")
graph.add_edge(edge)
edge = pydot.Edge("Modularization - Class", "Encapsulation")
graph.add_edge(edge)
edge = pydot.Edge("Modularization - Class", "Inheritance")
graph.add_edge(edge)
edge = pydot.Edge("Modularization - Class", "Polymorphism")
graph.add_edge(edge)
edge = pydot.Edge("Hari 1", "Modularization - Package")
graph.add_edge(edge)
edge = pydot.Edge("Hari 1", "Modularization - Study Case - Pydot Usage")
graph.add_edge(edge)
graph.write_png('hari1.png')
